version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
